INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('วัดโสธรวรารามวรวิหาร','วัด','https://lh5.googleusercontent.com/p/AF1QipOTh2RVguR44YDYXslsqoV1Jan2StehniMxqnvX=w408-h306-k-no','https://goo.gl/maps/uDfx5CPPLzYAdR6b7','วัดโสธรวรารามวรวิหาร เดิมชื่อว่า วัดหงษ์ สร้างในสมัยกรุงศรีอยุธยาตอนปลาย ในรัชสมัยสมเด็จพระนารายณ์มหาราช เป็นที่ประดิษฐาน หลวงพ่อพุทธโสธร พระพุทธรูปคู่บ้านคู่เมืองของฉะเชิงเทรา');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('วัดปิตุลาธิราชรังสฤษฎิ์','วัด','https://lh5.googleusercontent.com/p/AF1QipNjuYn6K42YaVf5aoz2HUd01xymP4FpZoD9xLb3=w408-h306-k-no','https://goo.gl/maps/rimz1PLJHVn6wB7e7','วัดปิตุลาธิราชรังสฤษฎิ์หรือวัดเมืองเป็นโบราณสถานที่สำคัญอีกแห่งหนึ่ง ที่สร้างขึ้นเมื่อเกิดการสร้างบ้านแปลงเมืองของฉะเชิงเทราใน พ.ศ. 2377 พร้อมๆกับการสร้างป้อมและกำแพงเมืองเพื่อกำหนดขอบเขตของแปดริ้ว');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('วัดจีนประชาสโมสร','วัด','https://lh5.googleusercontent.com/p/AF1QipN6Z86PAyxoamWAfEe-djB4ofbnynhYxH8Ba7c6=w390-h298-k-no','https://goo.gl/maps/Ngn6TaeFF7KDu1g19','วัดจีนประชาสโมสรหรือเล่งฮกยี่ เป็นวัดจีนเก่าแก่ของจังหวัดฉะเชิงเทรา วัดพุทธนิกายมหายานขยายมาจากวัดเล่งเน่ยยี่ในกรุงเทพฯ สร้างในสมัยรัชกาลที่ 5 พ.ศ.2449 ที่มีคุณค่าด้านศิลปกรรมแบบจีน');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('วัดหัวสวน','วัด','https://lh5.googleusercontent.com/p/AF1QipPdyHg7ziA2M2WxP-eZrWAppxy2FYe4R64_e6LB=w397-h298-k-no','https://goo.gl/maps/ZXuJ5D16txKRG33H9','สำหรับอุโบสถสแตนเลส สร้างบนฐานคอนกรีตสูงจากพื้นดินด้วยฝีมือและแรงงานของพระลูกวัด มีรั้วสแตนเลส ลายธรรมจักรประดับ เสาหงส์คาบโคมไฟโดยรอบ ตัวอุโบสถสร้างจากสแตนเลสทั้งหลัง');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('วัดสมานรัตนาราม','วัด','https://lh5.googleusercontent.com/p/AF1QipPN10kXRKW8IdR4jktDXihZsiKEhLeb5j-sE_ML=w408-h272-k-no','https://goo.gl/maps/ew1LwhhQhxf6w12P7','วัดสมานตั้งอยู่ริมแม่น้ำปางประกงใกล้กับโครงการเขื่อนทดน้ำบางปะกง ภายในวัดเป็นที่ประดิษฐานของพระพิฆเนศปางนอนเสวยสุของค์ใหญ่ซึ่งประชาชนส่วนใหญ่นิยมมาสักการะบูชา');

INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('บ้านเมล่อน','ร้านอาหาร','https://lh5.googleusercontent.com/p/AF1QipPp2TZYmsheYp6D9zNNewHqIQ_wceBlCJDYmQkd=w524-h298-k-no','https://g.page/baanmelon?share','ของฝากก็คือ เมล่อนหอมหวานจากแหล่งปลูกเขาหินซ้อนใกล้พนมสารคาม ฉะเชิงเทรา ซึ่งหลายๆคนยังไม่รู้ว่าจังหวัดใกล้กรุงเทพฯอย่างฉะเชิงเทรานั้นมีสวนเมล่อนอยู่ด้วย');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('ตลาดบ้านใหม่เมืองแปดริ้ว','ร้านอาหาร','https://lh5.googleusercontent.com/p/AF1QipMRCpZMDDXDH4mKmg-SnV8wX-G8GB1kMyt0YnK2=w447-h298-k-no','https://goo.gl/maps/kozVQhrPtTpAcb1t7','เป็นตลาดเก่าอายุกว่า 100 ปี เป็นชุมชนชาวไทยเชื้อ สายจีน เมื่ออดีตสถานที่แห่งนี้มีความคับคั่งด้วยผู้คนที่มาประกอบอาชีพค้าขาย มีอาคารบ้านเรือนที่ปลูกสร้างติดกันริมน้ำ');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('ตลาดน้ำบางคล้า','ร้านอาหาร','https://lh5.googleusercontent.com/p/AF1QipOj5N6lbSAO7CnqVQGrw8kvZ_PipHSY5H7lhtlD=w426-h240-k-no','https://goo.gl/maps/FMhgEyUB2u3VuZKDA','ตลาดน้ำที่มีชื่อเสียงของอำเภอบางคล้า จังหวัดฉะเชิงเทรา มีลักษณะเป็นโป๊ะที่ยื่นลงสู่แม่น้ำบางปะกง');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('เรือนร่มไทร','ร้านอาหาร','https://lh5.googleusercontent.com/p/AF1QipOFWeW4W_KMFWdGqjT-1ZYKAO6WGaiWb0jXWxMR=w446-h298-k-no','https://goo.gl/maps/3HkkXoXMAnbmV5Kn9','ร้านอาหารไทยบรรยากาศร่มรื่น มองเห็นวิวแม่น้ำบางปะกงที่สำคัญเป็นร้านอาหารไทยที่ในเมนูมีรายการอาหารเจและอาหารมังสวิรัติ');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('บ้านไม้ริมน้ำ แปดริ้ว','ร้านอาหาร','https://lh5.googleusercontent.com/p/AF1QipPRlSP00AKwi3b8TNZyhPrFjCdkRmLijT06qBfC=w224-h298-k-no','https://goo.gl/maps/CqFJj5wUrvqRNft87','ตัวร้านดัดแปลงมาจากบ้านไม้สองชั้นเก่าแก่ ซึ่งมีอายุกว่า 70 ปีมาแล้ว บ้านไม้หลังนี้แต่เดิมเคยเป็นโรงแรมชื่อดังแห่งหนึ่งในแปดริ้ว');

INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('สวนไม้ธารารีสอร์ทแอนด์สปา','ที่พัก','https://lh5.googleusercontent.com/p/AF1QipN0PbLx7Iq068Njl9n8BHfDN5W5n4hAJb9i1EDL=w397-h298-k-no','https://goo.gl/maps/4CtnJUYpeKtZbb4x8','สวนไม้ธารารีสอร์ท มีบริการอำนวยความสะดวก ฝ่ายต้อนรับ 24 ชั่วโมง และที่ฝากกระเป๋าเดินทาง ที่พักมีบริการที่จอดรถฟรี ห้องพักพร้อมเครื่องปรับอากาศ');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Yenjit Resort','ที่พัก','https://lh5.googleusercontent.com/p/AF1QipOrnkiuw78Flh7a9fGGSd1ACC7Zi-AG-YvltZVI=w529-h298-k-no','https://goo.gl/maps/UFDX3bbgESrjHNv68','รีสอร์ทตั้งอยู่ใกล้กับสถานที่ท่องเที่ยวสำคัญของเมืองฉะเชิงเทราหลายแห่ง เช่น Phraya Srisunthornwohan Monument และ วัดโสธรวรารามวรวิหาร');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('The Brown House Hotel','ที่พัก','https://lh5.googleusercontent.com/p/AF1QipMYZdoQcx4g2CcKNohigfu4EYuf3c3RuQ9zcfho=w528-h298-k-no','https://goo.gl/maps/YLUfnj6t78wZo7VK7','ทำเลที่ตั้งซึ่งอยู่ห่างจากกลางใจเมืองเพียง 1 Km ผู้เข้าพักจึงเดินทางไปยังสถานที่ท่องเที่ยวต่างๆ ในเมืองได้อย่างรวดเร็วและง่ายดาย');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Heaven Hotel Chachoengsao','ที่พัก','https://lh5.googleusercontent.com/p/AF1QipMnLQWL0dRODQw076Ljml_vIka8R0kwHZ9ZVUKA=w458-h298-k-no','https://goo.gl/maps/SBvgzxcm6QozudR79','ตั้งอยู่ในจังหวัดฉะเชิงเทราและอยู่ห่างจากวัดปากน้ำโจโลไม่เกิน 19 กม. มีห้องอาหาร ห้องพักและอินเทอร์เน็ตไร้สาย (WiFi) ฟรี');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('OYO 396 Wises Hotel','ที่พัก','https://lh3.googleusercontent.com/proxy/eKICt6YRhmVnZrBjcKj6wWK4i3yppA9NPRC80t-V2wG-g6oedShagWIOp6_M7usiU8vOXsytVxqIgiN5VAH_xU2qkt8vWseAyL_5uflHDOhEPcHiuxb25oDxVW5jrJ12XpbGOCw8lxW83C6PLBZGqRUNQrvyPg=w408-h272-k-no','https://goo.gl/maps/p3F2d8BEdKPzqyVP8','สะดวกสบายใกล้กับสถานีรถไฟฉะเชิงเทรา เข้ามาในที่พักเผยให้เห็นบรรยากาศที่ร่าเริงและเป็นมิตร ห้องพักตกแต่งแบบเรียบง่ายที่ทำให้คุณรู้สึกเหมือนอยู่บ้านในช่วงระยะเวลาที่เข้าพัก');

INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Bang Pakong River','สถานที่ธรรมชาติ','https://lh5.googleusercontent.com/p/AF1QipM_2oH6Czdt09230ZuFzFJ8svY3ty5t-FQUi7Xf=w224-h298-k-no','https://goo.gl/maps/AAczzy78vU1gSzED9','แม่น้ำบางปะกงเป็นแม่น้ำสายหลักของฉะเชิงเทรา ค่อนข้างเงียบสงบ ไม่มีเรือสัญจรวุ่นวายมาก มีแต่เรือหากุ้งของชาวบ้าน แม่น้ำค่อนข้างไหลแรง');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('เขตรักษาพันธุ์สัตว์ป่าเขาอ่างฤาไน','สถานที่ธรรมชาติ','https://lh5.googleusercontent.com/p/AF1QipNadH_4vl4vpGfmqFKAzBRgVCYrPym2FzH6mUel=w408-h306-k-no','https://goo.gl/maps/2yau3BbxgcEncksV7','เป็นผืนป่าราบต่ำแห่งสุดท้ายของประเทศไทย มีพื้นที่ป่าปกคลุมเป็นบริเวณกว้างมีสัตว์ป่านานาชนิดและนกพันธุ์ต่าง ๆ อาศัยอยู่มากมาย และยังมี น้ำตกอ่างฤาไน หรือน้ำตกบ่อทอง');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('สวนปาล์ม ฟาร์มนก','สถานที่ธรรมชาติ','https://lh5.googleusercontent.com/p/AF1QipMZN7s8wARwIV9f3GS_4Q9fUY_cDTZDqDtHonAR=w486-h240-k-no','https://goo.gl/maps/Kjt1qwa6tgtEwcHE6','เป็นสถานที่ที่เพาะพันธุ์นกต่างประเทศที่หายาก เช่น นกพันธุ์บลู แอนด์โกลด์ สกาเล็ต กรีนวิง ไฮยาซิน หรือ นกกระตั้ว และจะตื่นตาตื่นใจกับบรรยากาศของต้นปาล์มกว่า 10 สายพันธุ์');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('มินิมูร่าห์ฟาร์ม','สถานที่ธรรมชาติ','https://lh5.googleusercontent.com/p/AF1QipOGItRCDkG2u3GPaIh5Io1CFqeyTwsMJ3H9YXaj=w408-h306-k-no','https://g.page/MiniMurrahFarm?share','เป็นการย่อส่วนการสาธิต การทำฟาร์มควายนม และเป็นแหล่งท่องเที่ยวเชิงเกษตรจากฟาร์มใหญ่ ซึ่งเป็นฟาร์มปิดนับเป็นฟาร์มควายนมแห่งแรกในประเทศไทย');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('ศูนย์ศึกษาการพัฒนาเขาหินซ้อนฯ','สถานที่ธรรมชาติ','https://lh5.googleusercontent.com/p/AF1QipO_O2sR4MnuAOwpSQjiZD56Nyag5uRvpVWCZKDJ=w298-h298-k-no','https://goo.gl/maps/vosFngcLBGGdBKJZ9','เป็นแหล่งรวบรวมการศึกษา ทดลอง วิจัย และการพัฒนาปรับปรุงพื้นที่ดินทรายจัดเพื่อเกษตรกรรม ซึ่งมีรูปแบบการให้บริการแบบเบ็ดเสร็จ ณ จุดเดียว');

INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Plachum Bistro','คาเฟ่','https://lh5.googleusercontent.com/p/AF1QipNGoKRDFd_18uzF3f0fU11b_JGRTbVzIcrYVSz7=w600-h600-p-k-no','https://g.page/plachumbistro?share','เป็นการรีโนเวทบ้านไม้เก่า อายุกว่า 50 ปีหลังนี้ ให้เป็นจุดพบปะ สังสรรค์ เป็นสถานที่แห่งกาลเวลาสำหรับผู้คนหลากยุคหลายสมัย');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Thanam Cafe','คาเฟ่','https://lh5.googleusercontent.com/p/AF1QipMqFDPQYBFzPafuBZt9hVOoH917iadWhhuMthig=w408-h306-k-no','https://goo.gl/maps/W3NNQbXQHNRvVpgS8','ร้านกาแฟที่ตั้งอยู่ในเมือง จังหวัดฉะเชิงเทรา เป็นร้านคาเฟ่ริมน้ำบรรยากาศสบายๆ ที่สามารถมองเห็นแม่น้ำบางปะกง ซึ่งเป็นแม่น้ำที่ไหลผ่านเมืองแปดริ้ว เหมาะสำหรับมานั่งชิว ผ่อนคลายใกล้กรุง');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('FLORIVA CAFE','คาเฟ่','https://lh5.googleusercontent.com/p/AF1QipN57xiMMVqMxN6e7wz74-9N6izKfCWCnl6hV9qH=w426-h240-k-no','https://goo.gl/maps/2dRpWfgKV6PZ5Fnt5','คาเฟ่ริมแม่น้ำบางปะกง ที่เปลี่ยนจากตึกแถวเก่ามาเป็นคาเฟ่สุดชิค ด้านหน้าเป็นตึกแถวกึ่งปูนกึ่งไม้ ส่วนด้านในเป็นแบบบ้านไม้');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Nava House Café','คาเฟ่','https://lh5.googleusercontent.com/p/AF1QipOxNAfF2DGDRT4qQnsH4ur1inkB24TmQ2M70rG7=w397-h298-k-no','https://goo.gl/maps/XaYSPRSAZTSpeBCk8','คาเฟ่ริมแม่น้ำบางปะกง กับบรรยากาศสบายๆ ตกแต่งด้วยโทนสีเทา และโต๊ะหินอ่อนให้อารมณ์เรียบหรู เหมาะสำหรับการมานั่งชิลหรือหามุมถ่ายภาพเก๋ๆด้านในร้าน');
INSERT INTO PLACE(place_name,category,linkimg,linkmap,description) VALUES('Thakham cafe','คาเฟ่','https://lh5.googleusercontent.com/p/AF1QipOPweD-i4H_Qv6NjXCIxNuURQjhU6CHBIc-Y3Ab=w278-h298-k-no','https://g.page/thakhamcafe?share','คาเฟ่น่ารักๆ รูปทรงบ้าน ภายในตกแต่งสไตล์มินิมอลที่มีกลิ่นอายของญี่ปุ่นนิดๆ ภายนอกมีสวนล้อมด้วยต้นไม้สีเขียวช่วยเพิ่มสีสันและความสดชื่นกับร้านได้เป็นอย่างดี');